// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-Ulp_pnchFnHZwv3XlKpZr2wGUkFz-s4',
    appId: '1:397944390896:web:6734fe96cc94a908a0ee35',
    messagingSenderId: '397944390896',
    projectId: 'cequejeveux-96202',
    authDomain: 'cequejeveux-96202.firebaseapp.com',
    storageBucket: 'cequejeveux-96202.firebasestorage.app',
    measurementId: 'G-G37SPRENML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC52waXCmCvfcz0AGQJrcZ6T3phPv_E44o',
    appId: '1:397944390896:android:0c9bd6747c4f5a1ea0ee35',
    messagingSenderId: '397944390896',
    projectId: 'cequejeveux-96202',
    storageBucket: 'cequejeveux-96202.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8faDOGHon7L0HULnouuh8L-VEPvNnwUE',
    appId: '1:397944390896:ios:99143955368140eca0ee35',
    messagingSenderId: '397944390896',
    projectId: 'cequejeveux-96202',
    storageBucket: 'cequejeveux-96202.firebasestorage.app',
    iosBundleId: 'com.example.cequejeveux',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8faDOGHon7L0HULnouuh8L-VEPvNnwUE',
    appId: '1:397944390896:ios:99143955368140eca0ee35',
    messagingSenderId: '397944390896',
    projectId: 'cequejeveux-96202',
    storageBucket: 'cequejeveux-96202.firebasestorage.app',
    iosBundleId: 'com.example.cequejeveux',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-Ulp_pnchFnHZwv3XlKpZr2wGUkFz-s4',
    appId: '1:397944390896:web:24d67be5a37ad077a0ee35',
    messagingSenderId: '397944390896',
    projectId: 'cequejeveux-96202',
    authDomain: 'cequejeveux-96202.firebaseapp.com',
    storageBucket: 'cequejeveux-96202.firebasestorage.app',
    measurementId: 'G-5QYZBDTYEE',
  );
}
